<?php
return array (
  'ss6-dev.caroptics.ru' => 
  array (
    2 => 
    array (
      'url' => 'custom/*',
      'app' => 'shop',
      'theme' => 'custom',
      'theme_mobile' => 'custom',
      'locale' => 'ru_RU',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'url_type' => '0',
      'type_id' => '0',
      'currency' => 'RUB',
      'stock_id' => '1',
      'public_stocks' => '0',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
    ),
    0 => 
    array (
      'url' => 'blog/*',
      'app' => 'blog',
      'theme' => 'caroptics',
      'theme_mobile' => 'caroptics',
      'locale' => 'ru_RU',
      'blog_url_type' => '1',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    1 => 
    array (
      'url' => '*',
      'app' => 'shop',
      'theme' => 'caroptics',
      'theme_mobile' => 'caroptics',
      'locale' => 'ru_RU',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'url_type' => '1',
      'type_id' => '0',
      'currency' => 'RUB',
      'stock_id' => '1',
      'public_stocks' => '0',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
    ),
  ),
);
